fix(ESDK): Correct Auth tag of EC when EC is empty (#253)

diff --git a/.github/workflows/library_net_tests.yml b/.github/workflows/library_net_tests.yml
--- a/.github/workflows/library_net_tests.yml
+++ b/.github/workflows/library_net_tests.yml
@@ -196,70 +196,86 @@ jobs:
           cd $NET_41_VECTOR_PATH
           npx -y @aws-crypto/integration-node decrypt -v $NET_41_VECTOR_PATH/net41.zip -c cpu
 
-      - name: Unzip ESDK-NET @ v4.0.0 Vectors
+      - name: Unzip ESDK-NET @ v4.0.0 Valid Vectors
         working-directory: ./AwsEncryptionSDK/runtimes/net/TestVectorsNative/TestVectors/resources
         shell: bash
         run: |
-          NET_400_VECTOR_PATH=$GITHUB_WORKSPACE/net400/vectors
-          mkdir -p $NET_400_VECTOR_PATH
-          DOWNLOAD_NAME=net4.0.0.zip
-          unzip -o -qq $DOWNLOAD_NAME -d $NET_400_VECTOR_PATH
+          NET_400_VALID_VECTORS=$GITHUB_WORKSPACE/v4Net400Valid/vectors
+          mkdir -p $NET_400_VALID_VECTORS
+          DOWNLOAD_NAME=valid-Net-4.0.0.zip
+          unzip -o -qq $DOWNLOAD_NAME -d $NET_400_VALID_VECTORS
 
-      - name: Run ESDK-NET @ v4.0.0 Vectors on .NET Framework net48 expect failure
-        continue-on-error: true
+      - name: Run ESDK-NET @ v4.0.0 Valid Vectors expect success
         working-directory: ./AwsEncryptionSDK/runtimes/net/TestVectorsNative/TestVectors
+        continue-on-error: true
         shell: bash
         run: |
-          NET_400_VECTOR_PATH=$GITHUB_WORKSPACE/net400/vectors
+          NET_400_VALID_VECTORS=$GITHUB_WORKSPACE/v4Net400Valid/vectors
           ESDK_NET_V400_POLICY="forbid" \
-          DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_VECTOR_PATH/manifest.json" \
-          dotnet test --framework net6.0 &> /dev/null
+          DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_VALID_VECTORS/manifest.json" \
+          dotnet test --framework net48
+          ESDK_NET_V400_POLICY="forbid" \
+          DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_VALID_VECTORS/manifest.json" \
+          dotnet test --framework net6.0 --logger "console;verbosity=quiet"
+
+      - name: Unzip ESDK-NET @ v4.0.0 Invalid Vectors
+        working-directory: ./AwsEncryptionSDK/runtimes/net/TestVectorsNative/TestVectors/resources
+        shell: bash
+        run: |
+          NET_400_INVALID_VECTORS=$GITHUB_WORKSPACE/v4Net400Invalid/vectors
+          mkdir -p $NET_400_INVALID_VECTORS
+          DOWNLOAD_NAME=invalid-Net-4.0.0.zip
+          unzip -o -qq $DOWNLOAD_NAME -d $NET_400_INVALID_VECTORS
+
+      - name: Run ESDK-NET @ v4.0.0 Invalid Vectors .NET 48 expect failure
+        working-directory: ./AwsEncryptionSDK/runtimes/net/TestVectorsNative/TestVectors
+        continue-on-error: true
+        shell: bash
+        run: |
+          NET_400_INVALID_VECTORS=$GITHUB_WORKSPACE/v4Net400Invalid/vectors
+          ESDK_NET_V400_POLICY="forbid" \
+          DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_INVALID_VECTORS/manifest.json" \
+          dotnet test --framework net48
           # Dotnet test returns 1 for failure.
           TEMP=$?; if [[ "$TEMP" -eq 1 ]]; then true; else false; fi;
           # We want this to fail, so if it returned 1, step passes, else it fails
+          # TODO Post-#619: Refactor Test Vectors to expect failure,
+          # as I doubt this true false logic works
 
-      - name: Run ESDK-NET @ v4.0.0 Vectors on .NET Framework net48 expect success
+      - name: Run ESDK-NET @ v4.0.0 Invalid Vectors .NET 6.0 expect failure
         working-directory: ./AwsEncryptionSDK/runtimes/net/TestVectorsNative/TestVectors
-        shell: bash
-        run: |
-          NET_400_VECTOR_PATH=$GITHUB_WORKSPACE/net400/vectors
-          DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_VECTOR_PATH/manifest.json" \
-          dotnet test --framework net6.0
-          
-      - name: Run ESDK-NET @ v4.0.0 Vectors on .NET Framework net6.0 expect failure
         continue-on-error: true
-        working-directory: ./AwsEncryptionSDK/runtimes/net/TestVectorsNative/TestVectors
         shell: bash
         run: |
-          NET_400_VECTOR_PATH=$GITHUB_WORKSPACE/net400/vectors
+          NET_400_INVALID_VECTORS=$GITHUB_WORKSPACE/v4Net400Invalid/vectors
           if [ "$RUNNER_OS" == "macOS" ]; then
             ESDK_NET_V400_POLICY="forbid" \
-            DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_VECTOR_PATH/manifest.json" \
-            DYLD_LIBRARY_PATH="/usr/local/opt/openssl@1.1/lib" \
-            dotnet test --framework net6.0 &> /dev/null
-            # Dotnet test returns 1 for failure.
-            TEMP=$?; if [[ "$TEMP" -eq 1 ]]; then true; else false; fi;
-            # We want this to fail, so if it returned 1, step passes, else it fails
-          else
-            ESDK_NET_V400_POLICY="forbid" \
-            DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_VECTOR_PATH/manifest.json" \
-            dotnet test --framework net6.0 &> /dev/null
-            # Dotnet test returns 1 for failure.
-            TEMP=$?; if [[ "$TEMP" -eq 1 ]]; then true; else false; fi;
-            # We want this to fail, so if it returned 1, step passes, else it fails
-          fi
-
-      - name: Run ESDK-NET @ v4.0.0 Vectors on .NET Framework net6.0 expect success
-        working-directory: ./AwsEncryptionSDK/runtimes/net/TestVectorsNative/TestVectors
-        shell: bash
-        run: |
-          NET_400_VECTOR_PATH=$GITHUB_WORKSPACE/net400/vectors
-          if [ "$RUNNER_OS" == "macOS" ]; then
-            DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_VECTOR_PATH/manifest.json" \
+            DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_INVALID_VECTORS/manifest.json" \
             DYLD_LIBRARY_PATH="/usr/local/opt/openssl@1.1/lib" \
             dotnet test --framework net6.0
           else
-            DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_VECTOR_PATH/manifest.json" \
+            ESDK_NET_V400_POLICY="forbid" \
+            DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_INVALID_VECTORS/manifest.json" \
             dotnet test --framework net6.0
           fi
+          # Dotnet test returns 1 for failure.
+          TEMP=$?; if [[ "$TEMP" -eq 1 ]]; then true; else false; fi;
+          # We want this to fail, so if it returned 1, step passes, else it fails
+          # TODO Post-#619: Refactor Test Vectors to expect failure,
+          # as I doubt this true false logic works
           
+      - name: Run ESDK-NET @ v4.0.0 Invalid Vectors .NET expect Success
+        working-directory: ./AwsEncryptionSDK/runtimes/net/TestVectorsNative/TestVectors
+        shell: bash
+        run: |
+          NET_400_INVALID_VECTORS=$GITHUB_WORKSPACE/v4Net400Invalid/vectors
+          DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_INVALID_VECTORS/manifest.json" \
+          dotnet test --framework net48 --logger "console;verbosity=quiet"
+          if [ "$RUNNER_OS" == "macOS" ]; then
+            DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_INVALID_VECTORS/manifest.json" \
+            DYLD_LIBRARY_PATH="/usr/local/opt/openssl@1.1/lib" \
+            dotnet test --framework net6.0 --logger "console;verbosity=quiet"
+          else
+            DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="$NET_400_INVALID_VECTORS/manifest.json" \
+            dotnet test --framework net6.0 --logger "console;verbosity=quiet"
+          fi
